################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}/

################################################################################
####  MOMERS ####

### Liste des momers

GET {{endpoint}}api/momers
Authorization: token 


### Liste pour 1 momer

GET {{endpoint}}api/momers/1
Authorization: token 

#################################################################################
#### MUSICOS ####

### liste des musicos
GET {{endpoint}}api/musicos
Authorization: token 

### liste pour 1 musicos
GET {{endpoint}}api/musicos/25
Authorization: token 

### liste des musicos avec type of music 1
GET {{endpoint}}api/musicos?musical_type[]=1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6ImJlcm5hcmQiLCJwaWN0dXJlX3VybCI6Imh0dHBzOi8vaS5waW5pbWcuY29tL29yaWdpbmFscy8zOC9hYS8xMy8zOGFhMTM4NmFlNTI3MTFiMzE2MzAzMWU4ZGMzZjhiMy5qcGciLCJjaXR5IjoicGFyaXMiLCJlbWFpbCI6ImJlcm5hcmRAbWFpbC5mciIsInBhc3N3b3JkIjoiJDJhJDEyJHMzRG1vWHlUM3dobnNhMGRJRmt1QXVkeTFyTi9DOTFTeVUuZjNTWWQyRlhqeDF2UXFzRFA2IiwicGhvbmUiOiIrMzM2ODgyODQyODAiLCJhZGRyZXNzIjoiNzggcnVlIGRlcyBtYXJpbGxvbnMiLCJjb3VudHkiOiJpbGUgZGUgZnJhbmNlIiwicm9sZSI6Im1vbWVyIiwiZGVzY3JpcHRpb24iOiJiYXIgZGFucyB1bmUgYW1iaWFuY2UgZGUgcHViIGF2ZWMgc29pcmVlIGpldXggZGUgc29jaWV0ZXMgbGVzIG1hcmRpIiwibXVzaWNpYW5zX251bWJlciI6bnVsbCwiZ3JvdXBfbGVhZGVyIjpudWxsLCJleHRlcm5hbF91cmwiOiJsaWVuIGV4dGVybmUyIG1vbWVyIiwibW9tZXJfdG9fY29udGFjdCI6ImJlcm5hcmQiLCJtb21lcl90eXBlX2lkIjoxLCJjcmVhdGVkX2F0IjoiMjAyMi0wOS0wMlQxMjowMTo0NS43NzlaIiwidXBkYXRlZF9hdCI6bnVsbCwiaWF0IjoxNjYyMzg1NDc2LCJleHAiOjE2NjI0MDA0NzZ9.8bqKHwvi4m3rAx97dGjV-ZAifEk4nFi_uf04Dkje_Zc

###################################################################################
#### EVENT PUBLIE ####

### LIste des events publiés

GET {{endpoint}}api/
Authorization: token 

### Liste de 1 event

GET {{endpoint}}api/2

###################################################################################
#### ANNONCE ####

### Récupérer la liste des annonces

GET {{endpoint}}api/ads
Authorization: token

### Récupérer 1 annonce

GET {{endpoint}}api/ads/1
Authorization: token 

### créer une annonce

POST {{endpoint}}api/ads
Authorization: token 
content-type: application/json

{
    "name" : "testad",
    "description": "testad",
    "picture_url": "testad", 
    "owner_id": 1,
    "address": "testad",
    "county": "testad", 
    "city": "testad",
    "event_date": "25-08-2022", 
    "external_link": "testad", 
    "event_type": "testad",
    "type_of_music_needed": "testad"
}

##################################################################################
#### USER ####

### enregistrer un user
POST {{endpoint}}api/signup
content-type: application/json

{
    "name": "test",
    "email": "test3@mail.fr",
    "city": "aa",
    "county": "aa",
    "role": "musicos",
    "password": "D111azea",
    "password2": "D111azea"
}

### Visualiser son profil
GET {{endpoint}}api/profile
Authorization: token 

### Modifier son profil
PATCH {{ endpoint }}api/profile
Authorization: token 
content-type: application/json

{
    "name": "name3",
    "picture_url": "picture_url3",
    "city":"city3",
    "email":"email@email3.fr",
    "password":"password3",
    "phone":"0505050505",
    "address":"address3",
    "county":"county3",
    "description":"description3",
    "external_url": "external_url3",
    "momer_to_contact":"momer3",
    "group_leader": "test",
    "momer_type_id": 2,
    "musical_type": [1, 2]
}



### Supprimer de son profil

DELETE {{endpoint}}api/profile
Authorization: token 

### connexion d'un momer
POST {{endpoint}}api/signin
content-type: application/json

{
    "email": "carla@mail.fr",
    "password": "111"
}

###connexion d'un musicos
POST {{endpoint}}api/signin
content-type: application/json

{
    "email": "claudine@mail.fr",
    "password": "111"
}

#####################################################################################
#### MES ANNONCES #####

### Visualiser mes annonces
GET {{endpoint}}api/myads
Authorization: token 

### Visualiser une des mes annonces
GET {{endpoint}}api/myads/12
Authorization: token 
### Supprimer une annonce
DELETE {{endpoint}}api/myads/5
Authorization: token 

### Modification d'une annonce

PATCH {{endpoint}}api/myads/3
Authorization: token 
content-type: application/json 

{
    "name": "test1",
    "description":"test",
    "picture_url":"test",
    "address": "test",
    "is_published": false,
    "is_archived": false,
    "county": "test",
    "city": "test",
    "event_date": "25-08-2022",
    "external_link": "test",
    "event_type": "test",
    "type_of_music_needed": "test"
}

### Visualiser une candidature à une de mes annonces
GET {{endpoint}}api/myads/12/40
Authorization: token 

### Modifier le statut d'un candidature à une de mes annonces

PATCH {{endpoint}}api/myads/1/3
Authorization: token 
content-type: application/json 

{
    "candidate_status_id": 3
}

######################################################################################
#### MES EVENTS ####

### Visualiser mes events
GET {{endpoint}}api/myevents
Authorization: token 

### Visualiser une des mes event
GET {{endpoint}}api/myevents/15
Authorization: token 


### Supprimer un event
DELETE {{endpoint}}api/myevents/2
Authorization: token 

### Modification d'un event

PATCH {{endpoint}}api/myevents/4
Authorization: token 
content-type: application/json

{
    "name": "test",
    "description":"test",
    "picture_url":"test",
    "address": "test",
    "is_published": true,
    "is_archived": false,
    "county": "test",
    "event_date": "2022-08-25 14:34:45.13344+02",
    "external_link": "test",
    "event_type": "test",
    "type_of_music_needed": "test"
}

######################################################################################
#### MES CANDIDATURES ####

### Visualiser mes candidatures
GET {{endpoint}}api/myapplications
Authorization: token 

### Visualiser une des mes candidature

GET {{endpoint}}api/myapplications/2
Authorization: token 

### Supprimer une candidature
DELETE {{endpoint}}api/myapplications/2
Authorization: token 



